DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    created_at TIMESTAMP
);


DROP TABLE IF EXISTS url_checks;

CREATE TABLE url_checks (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url_id INT REFERENCES urls(id),
    status_code INT,
    h1 TEXT,
    title TEXT,
    description TEXT,
    created_at TIMESTAMP
);

